"""Is the synthesis still current with the answers on disk?

`docs/research/SYNTHESIS.md` is the decision record — where the research passes agree, disagree,
and contradict something already built. It is written by hand, because reconciling six documents
is judgement and a script that concatenated them would be producing a *collation* while calling
itself a synthesis.

What is NOT judgement is whether it has fallen behind. It had: written 2026-08-21 covering R1–R4,
it did not mention R5 or R6 at all, and nothing said so. That is the same shape as the readiness
table advertising 25 gates against a set of 30 — a generated-from-reality document quietly
describing an earlier reality.

So there is no "synthesize" button. There is a measurement of the gap, a test that fails on it,
and a generated prompt for a human-or-session to do the actual reconciling.

⚠ **What this cannot check.** That the synthesis is *correct*, or that it engaged with an answer
rather than name-dropping it. Mentioning `R6` once satisfies this module. It catches the failure
that actually happened — an answer landing and the record never being touched — and nothing
subtler. Do not read a pass here as "the synthesis is good".
"""
from __future__ import annotations

import hashlib
import pathlib
import re
from typing import Dict, List, Optional

RESEARCH = pathlib.Path(__file__).resolve().parent.parent / "docs" / "research"
SYNTHESIS = RESEARCH / "SYNTHESIS.md"
ANSWERS = RESEARCH / "answers"

#: R5-answer-build-velocity.md -> "R5"
_STEM = re.compile(r"^(R\d+)-answer", re.I)


def filed() -> Dict[str, pathlib.Path]:
    """Research id -> its filed answer. Follow-up answers count as their own id's answer."""
    out: Dict[str, pathlib.Path] = {}
    if not ANSWERS.is_dir():
        return out
    for f in sorted(ANSWERS.glob("R[0-9]*.md")):
        m = _STEM.match(f.name)
        if m:
            out.setdefault(m.group(1).upper(), f)
    return out


def _prose() -> str:
    """SYNTHESIS.md with the machine-written bank block removed.

    ⛔ **Load-bearing, and it was not obvious.** `bank()` writes every banked id into the block,
    and `synthesised()` scans the file for `R\\d+`. Without this strip, banking an answer would
    make it "mentioned" — so `outstanding()["banked_but_unmentioned"]`, the cross-check that
    exists precisely because a hash can be stamped by something that never read the answer, could
    never fire. An inert control, inside the control added to prevent one. Its own test caught it.
    """
    if not SYNTHESIS.is_file():
        return ""
    text = SYNTHESIS.read_text(encoding="utf-8")
    if _BANK_START in text and _BANK_END in text:
        head, rest = text.split(_BANK_START, 1)
        _, tail = rest.split(_BANK_END, 1)
        return head + tail
    return text


def synthesised() -> List[str]:
    """Research ids the synthesis mentions at all. Deliberately a low bar — see the module note."""
    return sorted({m.upper() for m in re.findall(r"\bR\d+\b", _prose())})


# ---------------------------------------------------------------------------------------------
# Banking by CONTENT, not by clock. See docs/findings.d/F93.

#: The machine-written block inside SYNTHESIS.md. Fenced so the writer can replace it whole
#: without touching a word of the prose around it — F82's lesson, where `pin_corpus.py` demanded
#: a `--why` for auditability and then destroyed every comment line in the file it rewrote.
_BANK_START = "<!-- BANKED-ANSWERS: generated by factory.synthesis.bank(). Do not hand-edit. -->"
_BANK_END = "<!-- /BANKED-ANSWERS -->"
_BANK_ROW = re.compile(r"^\s*(R\d+)\s+([0-9a-f]{6,64})\s*$", re.M)


def answer_hash(path: pathlib.Path) -> Optional[str]:
    """sha256 of an answer's bytes, truncated. None when it cannot be read.

    ⭐ Not a new idea in this estate — it is the third application of one that already works.
    `evals/MANIFEST.sha256` pins the corpus and is verified on load, and `registry.py:104-113`
    hashes a workflow's own text as its version on the stated ground that *"a SKILL.md edited
    between two runs is a different workflow."* An answer edited after the synthesis read it is a
    different answer.
    """
    try:
        return hashlib.sha256(path.read_bytes()).hexdigest()[:12]
    except OSError:
        return None


def banked() -> Dict[str, str]:
    """research id -> the answer hash the synthesis recorded when it folded that answer in.

    Empty when the block is absent, which is the honest reading: nothing has been banked by
    content. `bank()` seeds it.
    """
    if not SYNTHESIS.is_file():
        return {}
    text = SYNTHESIS.read_text(encoding="utf-8")
    try:
        block = text.split(_BANK_START, 1)[1].split(_BANK_END, 1)[0]
    except IndexError:
        return {}
    return {m.group(1).upper(): m.group(2) for m in _BANK_ROW.finditer(block)}


def bank(ids=None) -> Dict[str, str]:
    """Record the current hash of each named answer (default: every filed answer) and write the
    block back. Returns the new mapping.

    ⛔ **It rewrites the block and nothing else.** The prose is split on the markers and rejoined
    around a freshly rendered body, so no amount of editing here can touch a line a human wrote.
    That constraint is F82, which this repo has already paid for once: a writer that destroys the
    record it exists to keep.

    ⚠ Banking is a claim that the synthesis has taken an answer in. Nothing here can check that
    it did — see the module note. What it can do, which mtime could not, is make the claim
    **per answer**, so a partial pass banks only what it stamps.
    """
    have = filed()
    targets = sorted(have) if ids is None else [str(i).upper() for i in ids]
    out = dict(banked())
    for rid in targets:
        p = have.get(rid)
        h = answer_hash(p) if p else None
        if h:
            out[rid] = h
    body = "\n".join(f"{rid}  {out[rid]}" for rid in sorted(out, key=_num))
    rendered = f"{_BANK_START}\n```\n{body}\n```\n{_BANK_END}"

    text = SYNTHESIS.read_text(encoding="utf-8") if SYNTHESIS.is_file() else ""
    if _BANK_START in text and _BANK_END in text:
        head, rest = text.split(_BANK_START, 1)
        _, tail = rest.split(_BANK_END, 1)
        text = head + rendered + tail
    else:
        text = text.rstrip("\n") + "\n\n" + rendered + "\n"
    SYNTHESIS.write_text(text, encoding="utf-8")
    return out


def unsynthesised() -> List[str]:
    """Answers on disk the synthesis has never mentioned. Empty is the healthy state."""
    seen = set(synthesised())
    return sorted(rid for rid in filed() if rid not in seen)


def _num(rid: str) -> int:
    return int(rid[1:])


def outstanding() -> Dict[str, List[str]]:
    """Three distinct claims about an answer, kept apart because they need different remedies.

    ``never_banked``  no hash was ever recorded — the synthesis has not taken it in at all.
    ``stale``         a hash was recorded and the answer has changed since; the record describes
                      an earlier version of it.
    ``banked_but_unmentioned``  a hash exists but the prose never names the id.

    ⛔ **Both of the first two must drive the prompt, and until 2026-08-29 only one did.**
    `prompt()` used `unsynthesised()` alone and `session_prompt()` used
    ``unsynthesised() or unreconciled()`` — an `or`, so the stronger check was consulted only when
    the weaker one was already satisfied. That produced a reconciliation session told to fold in
    R19 while the page beside it reported R14, R18 and R19 outstanding.

    ⭐ **The third key is the cross-check that content-hashing makes necessary.** Under the old
    mtime basis the only way to satisfy the check was to edit the file after the answer landed,
    which is why the docstring called it blunt *and meant it as a compliment*. A hash can in
    principle be stamped by something that never read the answer — so a banked id that appears
    nowhere in the prose is reported rather than trusted. It is the same question `unsynthesised()`
    asks, pointed at the gap the new mechanism opens.

    The first two lists are disjoint by construction: a never-banked id is reported once, under
    the stronger reason.
    """
    rec = banked()
    never = sorted((r for r in filed() if r not in rec), key=_num)
    stale = sorted((r for r in unreconciled() if r not in never), key=_num)
    mentioned = set(synthesised())
    quiet = sorted((r for r in rec if r not in mentioned), key=_num)
    return {"never_banked": never, "stale": stale, "banked_but_unmentioned": quiet}


def prompt() -> str:
    """The paste text for actually doing the reconciling. Generated so it always names the real
    gap rather than whatever was outstanding when someone last wrote instructions down."""
    o = outstanding()
    never, late, quiet = o["never_banked"], o["stale"], o["banked_but_unmentioned"]
    gap = never + late
    if not gap:
        tail = ("" if not quiet else
                f" ⚠ {', '.join(quiet)} carry a banked hash but are named nowhere in the prose — "
                "a hash can be stamped by something that never read the answer, so check those "
                "by hand.")
        return ("SYNTHESIS.md has banked every filed answer at its current content. Nothing to "
                "reconcile — but note that banking records that an answer was folded in, not "
                "that it was engaged with." + tail)

    def _row(rid: str, why: str) -> str:
        f = filed().get(rid)
        if f is None:
            return f"  - {rid}: (answer file not found under docs/research/answers/) — {why}"
        return (f"  - {rid}: docs/research/answers/{f.name} "
                f"({f.stat().st_size:,} bytes) — {why}")

    listing = "\n".join(
        [_row(r, "NEVER BANKED — the synthesis has not taken it in at all") for r in never]
        + [_row(r, "banked, but the answer has CHANGED since — whatever the record says about it "
                   "describes an earlier version") for r in late])

    if never and late:
        why = (f"It has never banked {', '.join(never)}, and {', '.join(late)} changed after "
               f"being banked.")
    elif never:
        why = f"It has never banked {', '.join(never)}."
    else:
        why = (f"{', '.join(late)} changed after being banked, so anything it says about them "
               "describes an earlier version.")

    return f"""Update docs/research/SYNTHESIS.md, which is the decision record for this programme's
research. {why}

⛔ Fold in ALL of them in one pass, then run `python -c "from factory import synthesis;
synthesis.bank()"` to record what you took in. Banking is per answer, so a partial pass banks only
what it stamps — but an answer left out of this pass stays outstanding rather than being quietly
carried, which is the point.

SYNTHESIS.md already has a structure — convergence, what we got right, what we got wrong,
corrections to things said in session, build order, what not to build, where the answers disagree,
what changes in this repo. Extend those sections rather than bolting on a new one per answer.

Hold to what the existing document does well, which is refusing to smooth:

  - Where a new answer DISAGREES with an earlier one, or with something already built or already
    said, record the disagreement and which evidence is stronger. Do not average them.
  - Label every recommendation by the basis its source gave it — OBSERVED in a comparable setting
    versus EXTRAPOLATED from human teams. R6 labelled its own; R5 partly did.
  - ⚠ Read docs/findings.md F7 first. One of these answers was produced under a FALSE CONSTRAINT
    that I wrote into its prompt, and it demonstrably changed the ranking. The synthesis has to
    say so, or it will carry the distortion forward as a finding.
  - Say what the answers could NOT settle. Both declared their own gaps; those belong in the
    record as much as the conclusions.

Then re-run `python -m pytest tests/test_synthesis_current.py` — it fails while any filed answer
goes unmentioned."""


def unreconciled() -> List[str]:
    """Answers whose current content is not what the synthesis banked.

    Same question as before — *has something landed that the record has not taken in?* — asked of
    CONTENT instead of the clock. An id is unreconciled when no hash was ever recorded for it, or
    when the answer on disk no longer hashes to the one that was.

    ⛔ **This used to compare modification times, and that was F93.** `git worktree add` writes
    every file at once: measured 2026-08-31, `SYNTHESIS.md` landed at `04:52:31.012` and all
    eighteen answers five milliseconds later, so **every** answer read as "filed after" on
    write-ordering alone. In the primary checkout the same call returned `[]`. Any fresh clone —
    including a first CI run, which this repo does not yet have and which is the only reason it
    never fired — opened with eighteen phantom items. An mtime is a fact about a checkout, not
    about the work.

    ⭐ **It also fixes the defect the old docstring called unacceptable in itself.** Modification
    time is one number for the whole file, so *any* write cleared the check for *every* id — a
    partial reconciliation marked the answers it never opened as banked. The 2026-08-29 correction
    recorded that and could only answer it with a rule ("a partial write must never happen").
    Hashes are per answer, so a partial pass can bank only what it stamps. The rule is now a
    property.

    ⚠ Unchanged, and worth restating: this cannot tell whether the synthesis *engaged* with an
    answer. Banking is a claim, and the cross-check for a claim made without writing anything is
    `outstanding()["banked_but_unmentioned"]`.
    """
    have = filed()
    if not have:
        return []
    rec = banked()
    out = []
    for rid, path in have.items():
        cur = answer_hash(path)
        if cur is None:
            continue                       # unreadable is NOT-VISIBLE, not stale
        if rec.get(rid) != cur:
            out.append(rid)
    return sorted(out, key=_num)


# ---------------------------------------------------------------------------------------------
# Launching the reconciliation, rather than only describing it.
#
# ⛔ The Research tab used to carry a comment saying there is deliberately NO synthesize button,
# "because synthesis is judgement, and a button that cannot exercise it would either fake it or
# do nothing". That reasoning was correct WHEN THE ONLY MECHANISM WAS A PASTE LOOP — and it is
# superseded by the same thing that superseded the paste loop for research passes: a button can
# now open a Claude Code session in this repo that actually does the work.
#
# The objection is answered rather than ignored. The button does not exercise judgement; it
# DISPATCHES judgement to an agent and records that it did, exactly as `/research/start` does. A
# reconciliation run locally is less independent than a human reading the answers cold, and the
# run note says so, because that is what tells the next reader how to weigh the record.
#
# ⚠ What it still cannot do is make the reconciliation GOOD. `unsynthesised()` checks mention and
# `unreconciled()` checks modification time; neither checks engagement, and a session that writes
# one sentence per answer clears both. That gap is unchanged by this button and is stated on the
# page rather than papered over.


def session_prompt() -> str:
    """What the launched reconciling session is told.

    Wraps :func:`prompt` — which already names the real gap — with the three rules a session
    working in a shared checkout needs, and the run-provenance stamp.
    """
    o = outstanding()
    gap = o["never_banked"] + o["stale"]
    return f"""Reconcile the research record.

{prompt()}

⛔ You may write EXACTLY ONE file: docs/research/SYNTHESIS.md. Do NOT `git add`, commit, stage, or
edit any other file — other sessions are working in this checkout right now, and the answers you
are reading are inputs, not drafts to tidy.

⛔ READ THE ANSWERS IN FULL before writing anything. The failure this reconciliation exists to end
is a record that talks about an answer nobody read: on 2026-08-23 SYNTHESIS.md said three times
that R8 was "still outstanding" while its answer sat filed on disk, and the mention-check went
green over it. Writing the id into a sentence is what a broken run looks like.

⛔ Do NOT smooth a disagreement. Where an answer contradicts an earlier one, or something already
built, record both and say which evidence is stronger and why. Averaging two findings produces a
third that nobody measured.

When you finish, append one line to the end of SYNTHESIS.md recording HOW this pass ran:
reconciled locally by an agent with repo access — stronger on file-and-line claims, less
independent than a reader coming to the answers cold. Both halves.

Outstanding when this session started: {', '.join(gap) if gap else 'nothing'}.
"""
