-- Rollback for scripts/grant_reader_refresh.py --apply
-- Written 2026-09-03T14:02:30.269180+00:00 BEFORE the grants were issued.
-- Run as ACCOUNTADMIN. Revokes FUTURE first; see the module docstring for why.
USE ROLE ACCOUNTADMIN;
REVOKE SELECT ON FUTURE VIEWS IN SCHEMA TEST_DG1_GEP.WAREHOUSE FROM ROLE R3_CARTOGRAPHY_RO;
REVOKE SELECT ON FUTURE TABLES IN SCHEMA TEST_DG1_GEP.WAREHOUSE FROM ROLE R3_CARTOGRAPHY_RO;
REVOKE SELECT ON ALL VIEWS IN SCHEMA TEST_DG1_GEP.WAREHOUSE FROM ROLE R3_CARTOGRAPHY_RO;
REVOKE SELECT ON ALL TABLES IN SCHEMA TEST_DG1_GEP.WAREHOUSE FROM ROLE R3_CARTOGRAPHY_RO;
